# Generated by Django 6.0.3 on 2026-03-18 21:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='invite_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='telegram_verified',
            field=models.BooleanField(default=False),
        ),
    ]
