# Generated by Django 6.0.3 on 2026-03-22 18:27

import uuid
from django.db import migrations, models


def populate_invite_tokens(apps, schema_editor):
    User = apps.get_model('users', 'User')

    for user in User.objects.filter(invite_token__isnull=True):
        token = uuid.uuid4()
        while User.objects.filter(invite_token=token).exists():
            token = uuid.uuid4()
        user.invite_token = token
        user.save(update_fields=['invite_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invite_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(populate_invite_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='invite_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
